### ISSUE TITLE
IntelliJ classpath issue when using project plugin with kotlin

### ISSUE THREAD

**Issue by jamesbassett** [nebula-plugins/nebula-project-plugin#23]
Hi, I'm just having some issues with the NebulaIntegTestPlugin and IntelliJ (2016.2) when using a multi-module gradle project.  This is only an IntelliJ issue - the integ test plugin + kotlin works fine via Gradle.

I've created a sample repo that reproduces the problem: https://github.com/jamesbassett/nebula-project-kotlin-issue

It has two modules (service and model). The service model has a `PersonFixture` in its test dir for creating a `Person` (defined in the model project). Using the fixture in the integ test succeeds when using Java but fails with the following error in kotlin:

    Cannot access class 'com.example.Person'. 
    Check your module classpath for missing or conflicting dependencies

I'm able to resolve the issue manually by doing the following to the `service_integTest` source set (i.e. selecting `service/src/integTest`, pressing F4 and configuring):

* Marking `service/src/integTest` as a test source directory (it get's incorrectly marked as sources for some reason)
* Copying the module compile output path from 'output path' to 'test output path'
* Adding a module dependency for `service_test`

I took a look at the [IdeaPluginConfigurer](https://github.com/nebula-plugins/nebula-project-plugin/blob/master/src/main/groovy/nebula/plugin/responsible/ide/IdeaPluginConfigurer.groovy) and how it configures the [IdeaModule](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.idea.model.IdeaModule.html), but I couldn't see anything that stood out.

Any ideas?  Thanks :)

**Comment by DanielThomas** [comment]
Frustrating, but an IntelliJ issue I'm afraid. When you link the Gradle project from a generated file (or import the project directly), IntelliJ clobbers assumes that anything but the `test` sourceset is a main sourceset - you'll find the same for any custom sourceset from 2016.1.

I'm sure someone has reported this with JetBrains (they really should assume any sourceset with 'test' in the name is test...); if you manage to find an issue, post it here and I'll give it a vote :)

**Comment by jamesbassett** [comment]
Yeah, I figured as much, but was hoping for an easy fix :)

I googled `intellij sourceset bug` and looks like I found it, first result!

https://youtrack.jetbrains.com/issue/IDEA-151925

**Comment by jamesbassett** [comment]
Looks like the latest intellij update (2016.2.3) works a bit better :)  Now I only have to mark `src/integTest/kotlin` as test sources and it all works. I can probably live with that until that ticket is resolved.
