### ISSUE TITLE
Test facets should inherit from test by default

### ISSUE THREAD

**Issue by karaken12** [nebula-plugins/nebula-project-plugin#24]
As in the title, really: the default should be to inherit from test.

**Comment by oehme** [comment]
They shouldn't, you don't want your integ tests to rerun just because a unit test changed.

**Comment by karaken12** [comment]
@oehme That's not what that does. All this change means is that it inherits the test _source set_, so you don't have to have duplicate lines like 
```
    testCompile group: 'junit', name: 'junit', version: '4.12'
    integTestCompile group: 'junit', name: 'junit', version: '4.12'
```
It doesn't affect how the tests run at all.

**Comment by oehme** [comment]
I must have misunderstood the "parentSourceSet" concept then. I assumed that it also means that a child can access the compiled classes of the parent (like `test` can access classes from `main`).

**Comment by oehme** [comment]
> That's not what that does. All this change means is that it inherits the test source set, so you don't have to have duplicate lines like

Look at the code here: https://github.com/nebula-plugins/nebula-project-plugin/blob/master/src/main/groovy/nebula/plugin/responsible/NebulaFacetPlugin.groovy#L117

The parent source set's output is added to the compile classpath. This means that integration tests are rerun every time a unit test changes.

**Comment by karaken12** [comment]
Ah, I see what you're saying. However I don't think it invalidates the point. It's common practice to use the `test` source set as a base for integration tests (and the like); see nebula.integtest for an example! It may be a better idea to have your fixtures in a separate source set, but if you don't then it only makes sense to have your other tests marked as not up-to-date if your `test` source set changes.

Please note that this change doesn't mean you _can't_ still have a `testFixtures` source set; it only changes the *default* for test facets.

**Comment by oehme** [comment]
>  It's common practice to use the test source set as a base for integration tests

It's a common mistake. It means that any change to a unit test will lead to rerunning all your integration tests. We should discourage that kind of mistake instead of enshrining it in a plugin.

**Comment by rpalcolea** [comment]
We agree with @oehme opinion and we don't consider this to be an issue to be fixed
