### ISSUE TITLE
Support implementation/runtimeOnly configurations

### ISSUE THREAD

**Issue by oehme** [nebula-plugins/nebula-project-plugin#31]
Since Gradle 3.4, every SourceSet has an `implementation` and `runtimeOnly` configuration, which should be preferred over `compile` and `runtime`. It would be great if the facet plugin added the relevant `extendsFrom()` relationships.

**Comment by rpalcolea** [comment]
This is now supported, forgot to close this ticket.

Thanks again for raising the issue @oehme
