### ISSUE TITLE
nebula.integtest report output location

### ISSUE THREAD

**Issue by LtTempletonPeck** [nebula-plugins/nebula-project-plugin#34]
Hi I have a question regarding the nebula.integtest report output location

I have a Java/Kotlin/Spring-Boot project that I have added the nebula.integtest plugin to. The unit tests produce a report to the build/reports/tests/test directory, the integration tests produce a report to build/reports/integTest. Is it by design the integration test report is not put in the tests subdirectory or a bug? Is it configurable?

**Comment by bronogard** [comment]
Hi, you can configure it explicitly - see https://github.com/nebula-plugins/nebula-project-plugin/issues/35
