### ISSUE TITLE
The integrationTest task never completes - doesn't actually run test.

### ISSUE THREAD

**Issue by gezerk** [nebula-plugins/nebula-project-plugin#36]
When I run the integrationTest task `./gradlew integrationTest` the task never completes and the test is not executed.  
I have a test in `src/integTest/groovy` that throws an exception.  Execution of the task stops at `Executing test`.
I verified this behavior with both `apply plugin: 'nebula.integtest-standalone'` and `apply plugin: 'nebula.integtest'`.
I am using ` Nebula 4.2.0 on Gradle 4.3.1`.

```./gradlew integTest

> Configure project : 
+===============================================================================
| Nebula 4.2.0 on Gradle 4.3.1
+===============================================================================
<===========--> 85% EXECUTING [11s]
> :integrationTest > 0 tests completed
> :integrationTest > Executing test com.company...listener.ThrowingIntegrationTest
```

**Comment by gezerk** [comment]
I notice that if I run `./gradlew check` my test is executed and the task completes.

**Comment by rpalcolea** [comment]
This isn't an issue anymore on modern versions of nebula and gradle
