### ISSUE TITLE
The 'integrationTest' task is unexpectedly called when running the 'test' task - 'nebula.integtest-standalone'

### ISSUE THREAD

**Issue by gezerk** [nebula-plugins/nebula-project-plugin#37]
According to the README.md the `integrationTest` task should not depend on the `check` task if the `'nebula.integtest-standalone'` plugin is applied.  I see the `integratationTask` is run when I execute `./gradlew check` .
I have done `apply plugin: 'nebula.integtest-standalone'`, I am running `Nebula 4.2.0 on Gradle 4.3.1`.

**Comment by rpalcolea** [comment]
This isn't an issue anymore on modern versions of nebula and gradle. We had this issue in the past but we verified it with newest a couple of weeks back
