### ISSUE TITLE
Gradle 4.6 still gives deprecation warning

### ISSUE THREAD

**Issue by remy-tiitre** [nebula-plugins/nebula-project-plugin#42]
I do see that there is a check for Gradle version and starting from 4.0 it should use the correct method, but for me it still gives a warning "The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead." with Gradle 4.6

**Comment by rpalcolea** [comment]
This should be fixed now as we now are also making sure we don't have deprecations for Gradle 6.0 and 7.0
