### ISSUE TITLE
Undocumented usage of DependencyLockPlugin and possibility to opt out

### ISSUE THREAD

**Issue by jonatan-ivanov** [nebula-plugins/nebula-project-plugin#68]
It seems that the plugin [depends on](https://github.com/nebula-plugins/nebula-project-plugin/blob/2061844d006bcc180251ce9dbd4de54023551248/build.gradle#L36) the [Dependency Lock Plugin](https://github.com/nebula-plugins/gradle-dependency-lock-plugin) and the [`NebulaResponsiblePlugin` applies it](https://github.com/nebula-plugins/nebula-project-plugin/blob/2061844d006bcc180251ce9dbd4de54023551248/src/main/groovy/nebula/plugin/responsible/NebulaResponsiblePlugin.groovy#L41). It seems this is not documented which can lead to surprises. :)

With the "native" dependency locking feature in Gradle, I feel doing this is less important to the users also, `DependencyLockPlugin` seems to break the [Gradle Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html).

Would it be possible to either remove the Dependency Lock Plugin or provide a flag so that users can avoid applying it?

**Comment by rpalcolea** [comment]
Hi @jonatan-ivanov , thanks for the report.

I'm releasing [8.1.0](https://github.com/nebula-plugins/nebula-project-plugin/releases/tag/v8.1.0) Today.

You can use `nebula.dependencyLockPluginEnabled` project property. It defaults to `true` for now. We might remove this in the future once we finish our migration from nebula dependency lock to gradle core locking 

I'll also update the README to reflect these changes.

**Comment by jonatan-ivanov** [comment]
@rpalcolea Thank you very much (extra thanks for the quick fix)!
